export type { ClosePrice, SigmaResult, HistoryRow, HistoryRowLite, SignalRow, RollingWindow } from './model/types'
export { ROLLING_WINDOWS } from './model/types'
export { calcDailyReturns, calcRolling252, calcOrderPrices, buildHistory, buildLatestSignal, buildSignalHistory } from './model/calc'
export { fetchCloses } from './api/fetchCloses'
export { stripHistoryWindow, stripHistoryRows } from './lib/stripHistoryWindow'
